Updated varnish distro repo/gpg, anchored the vmod version to 4.1
Financial-Times/k8s-pub-path-routing-varnish pull request #4
Opened 2018-05-01 11:08 UTC by erdema-ft

2018-05-02 06:11 UTC, tamas-molnar requested changes
Can you please deploy an RC in dev to validate the changes?

2018-05-02 10:44 UTC, erdema-ft commented
@tamas-molnar we usually do that after the code review if I'm not mistaken but sure I can do it.

P.S: I did the very same fix for the delivery varnish, fyi.

2018-05-02 10:46 UTC, erdema-ft commented
Released 1.1.1-k8s-varnish-dockerfile-fix-rc1

2018-05-03 09:39 UTC, tamas-molnar approved these changes

2018-05-03 10:55 UTC, merged